### ISSUE TITLE
Compression segfault

### ISSUE THREAD

**Issue by terrelln** [MartinezTorres/marlin#6]
I was attempting to run the C compressor on some data, and it is segfaulting with this stack:

```
=================================================================
==1615493==ERROR: AddressSanitizer: SEGV on unknown address 0x629000011200 (pc 0x000000491dc7 sp 0x7ffd655cc2d0 bp 0x603000075100 T0)
    #0 0x491dc6 in unsigned int& (anonymous namespace)::JumpTable::operator()<unsigned int, unsigned long, unsigned long>(unsigned int*, unsigned long const&, unsigned long const&) const (/data/users/terrelln/datasets/silesia-literals/marlin+0x491dc6)
    #1 0x491dc6 in marlin::TMarlinCompress<unsigned char, unsigned char>::buildCompressorTable(marlin::TMarlinDictionary<unsigned char, unsigned char> const&) const (/data/users/terrelln/datasets/silesia-literals/marlin+0x491dc6)
    #2 0x481546 in marlin::TMarlinCompress<unsigned char, unsigned char>::TMarlinCompress(marlin::TMarlinDictionary<unsigned char, unsigned char> const&) (/data/users/terrelln/datasets/silesia-literals/marlin+0x481546)
    #3 0x4810c8 in marlin::TMarlin<unsigned char, unsigned char>::TMarlin(std::string, marlin::TMarlinDictionary<unsigned char, unsigned char>) (/data/users/terrelln/datasets/silesia-literals/marlin+0x4810c8)
    #4 0x48088d in marlin::TMarlin<unsigned char, unsigned char>::TMarlin(std::string, std::vector<double, std::allocator<double> > const&, std::map<std::string, double, std::less<std::string>, std::allocator<std::pair<std::string const, double> > >) (/data/users/terrelln/datasets/silesia-literals/marlin+0x48088d)
    #5 0x48053b in Marlin_build_dictionary (/data/users/terrelln/datasets/silesia-literals/marlin+0x48053b)
    #6 0x47fce4 in main (/data/users/terrelln/datasets/silesia-literals/marlin+0x47fce4)
    #7 0x7f22bd17a444 in __libc_start_main (/lib64/libc.so.6+0x22444)
    #8 0x47f68c in _start (/data/users/terrelln/datasets/silesia-literals/marlin+0x47f68c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 unsigned int& (anonymous namespace)::JumpTable::operator()<unsigned int, unsigned long, unsigned long>(unsigned int*, unsigned long const&, unsigned long const&) const
==1615493==ABORTING
```

The program running is:

```c++
#include <assert.h>
#include <memory>
#include <stdio.h>

#include "marlin.h"

std::vector<double> buildHistogram(uint8_t const* buf, size_t size) {
  std::vector<double> histogram;
  histogram.resize(256);
  for (size_t i = 0; i < size; ++i) {
    ++histogram[buf[i]];
  }
  for (double& v : histogram) {
    v /= double(size);
  }
  return histogram;
}

int main() {
  size_t const kBufSize = 64 * 1024 * 1024;
  std::unique_ptr<uint8_t[]> buf(new uint8_t[kBufSize]);
  size_t const read = fread(buf.get(), 1, kBufSize, stdin);
  assert(read < kBufSize);
  auto hist = buildHistogram(buf.get(), read);
  auto* dict = Marlin_build_dictionary("dictionary", hist.data());

  std::unique_ptr<uint8_t[]> out(new uint8_t[kBufSize]);
  auto const ret = Marlin_compress(dict, out.get(), kBufSize, buf.get(), read);
  assert(ret >= 0);
  assert(ret <= read);
  if (ret == 0) {
    // Uncompressible.
    size_t const written = fwrite(buf.get(), 1, read, stdout);
    assert(written == read);
  } else if (ret == 1) {
    // RLE
    assert(read >= 1);
    size_t const written = fwrite(buf.get(), 1, 1, stdout);
    assert(written == 1);
  } else {
    // NORMAL
    fwrite(out.get(), 1, ret, stdout);
  }

  Marlin_free_dictionary(dict);
}
```

The data is literals leftover after compressing a zstd block from Silesia. I've attached the data (I had to zip it to appease GitHub). The command is:

```
./marlin < block-79
```

[block-79.zip](https://github.com/MartinezTorres/marlin/files/3005984/block-79.zip).

**Comment by MartinezTorres** [comment]
Hi terrelln, I saw the issue. The C pipeline was just vaguely tested. I'll invest time tomorrow on the issue!

**Comment by MartinezTorres** [comment]
Hi, this issue should be solved now. While searching for the best configuration, Marlin tried once to use 256 symbols in its internal dictionary. This causes an overflow, and there was a check in place specifically to prevent this, but sadly the check was off by 1.

**Comment by terrelln** [comment]
@MartinezTorres is this the right way to invoke Marlin if I want to test compression ratio and decompression speed (I don't care about compression speed right now) on the literals in zstd (that would normally be Huffman compressed)? Are there any parameters what I should be setting?

**Comment by MartinezTorres** [comment]
I would say that this is a very simplistic way of calling Marlin. While in other codecs such as Huffman and FSE the step of building the dictionary is fast in comparison to the decoding/encoding speed, this is not the case in Marlin. Due to the nature of the code, the dictionaries are big and complex to build, so if you send the encoded message together with the histogram, later, when you try to decode the message, you will spend a very significant amount of time rebuilding the dictionary.

So, for practical cases, it is better to use a number of prebuilt dictionaries that are known a priori to the encoder and decoder (i.e., in image compression we use prebuilt dictionaries with a Laplacian distribution). Then, when encoding a message, you select the best fitting dictionary from the ones you have available. 

The strategy you use to build and select those dictionaries is key for using Marlin effectively, and it depends on the application.

I guess that you can use your approach right know to get a gross estimate of the decoding speed and compression rate that you can achieve in this data, but before you apply Marlin to your application you will need to tackle the dictionary creation process. 

Note that the Marlin libraries already provides several pre-built dictionaries.

BTW, Thanks for taking a look at it ;)
